# version: 2
# updates:
#   - package-ecosystem: 'github-actions'
#     directory: '/'
#     schedule:
#       interval: 'monthly'
#       day: 'sunday'
#     assignees:
#       - 'tylerjlawson'

#   - package-ecosystem: 'npm'
#     directory: '/'
#     schedule:
#       interval: 'weekly'
#       day: 'sunday'
#     assignees:
#       - 'tylerjlawson'
