######################## default configuration ####################
baseURL = "https://tyler-lawson.com"
title = "Tyler Lawson"
theme = "somrat"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/css/all.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/hugrid/modernizr.custom.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Portfolio"
URL = "#portfolio"
weight = 3


#################### default parameters ################################
[params]
logo_light = "images/logo.svg"
logo_dark = "images/logo-dark.svg"
copyright = "Copyright &copy; 2021 Tyler Lawson"
# Meta data
description = "Personal Portfolio"
author = "Tyler Lawson"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/tylerjlawson"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/tyler-lawson-3a370b137/"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:tylerjlawson2@gmail.com"

contentDir = "content/english"
weight = 1
home = "Home"
