######################## default configuration ####################
baseURL = "https://tyler-lawson.com"
title = "Tyler Lawson"
theme = "port-hugo"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/#header"
weight = 1

[[menu.main]]
name = "About me"
URL = "/#about"
weight = 2

[[menu.main]]
name = "Portfolio"
URL = "/#portfolio"
weight = 3

[[menu.main]]
name = "Blog"
URL = "/blog"
weight = 4


#################### default parameters ################################
[params]
logo_light = "images/logo.svg"
logo_dark = "images/logo-dark.svg"
copyright = "Copyright Tyler Lawson &copy;"
# Meta data
description = "Personal Portfolio"
author = "Tyler Lawson"

[params.special_favicon]
apple_touch = "/favicon/apple-touch-icon.png"
fav32 = "/favicon/favicon-32x32.png"
fav16 = "/favicon/favicon-16x16.png"
manifest = "/favicon/manifest.json"
mask_icon = "/favicon/safari-pinned-tab.svg"
mask_icon_color = "#374a67"
theme_color = "#fff"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/tylerjlawson"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/tyler-lawson-3a370b137/"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:tylerjlawson2@gmail.com"

[[params.social]]
icon = "fab fa-medium"
link = "https://medium.com/@tylerjlawson2"

contentDir = "content/english"
weight = 1
home = "Home"
