name: Automerge dependabot
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and submodules (hugo theme)
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Hugo
        uses: srt32/hugo-action@v0.0.3

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.TOKEN }}
